/*
 * Globalize Culture he-IL
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "he-IL", "default", {
	name: "he-IL",
	englishName: "Hebrew (Israel)",
	nativeName: "עברית (ישראל)",
	language: "he",
	isRTL: true,
	numberFormat: {
		"NaN": "לא מספר",
		negativeInfinity: "אינסוף שלילי",
		positiveInfinity: "אינסוף חיובי",
		percent: {
			pattern: ["-n%","n%"]
		},
		currency: {
			pattern: ["$-n","$ n"],
			symbol: "₪"
		}
	},
	calendars: {
		standard: {
			days: {
				names: ["יום ראשון","יום שני","יום שלישי","יום רביעי","יום חמישי","יום שישי","שבת"],
				namesAbbr: ["יום א","יום ב","יום ג","יום ד","יום ה","יום ו","שבת"],
				namesShort: ["א","ב","ג","ד","ה","ו","ש"]
			},
			months: {
				names: ["ינואר","פברואר","מרץ","אפריל","מאי","יוני","יולי","אוגוסט","ספטמבר","אוקטובר","נובמבר","דצמבר",""],
				namesAbbr: ["ינו","פבר","מרץ","אפר","מאי","יונ","יול","אוג","ספט","אוק","נוב","דצמ",""]
			},
			eras: [{"name":"לספירה","start":null,"offset":0}],
			patterns: {
				d: "dd/MM/yyyy",
				D: "dddd dd MMMM yyyy",
				t: "HH:mm",
				T: "HH:mm:ss",
				f: "dddd dd MMMM yyyy HH:mm",
				F: "dddd dd MMMM yyyy HH:mm:ss",
				M: "dd MMMM",
				Y: "MMMM yyyy"
			}
		},
		Hebrew: {
			name: "Hebrew",
			"/": " ",
			days: {
				names: ["יום ראשון","יום שני","יום שלישי","יום רביעי","יום חמישי","יום שישי","שבת"],
				namesAbbr: ["א","ב","ג","ד","ה","ו","ש"],
				namesShort: ["א","ב","ג","ד","ה","ו","ש"]
			},
			months: {
				names: ["תשרי","חשון","כסלו","טבת","שבט","אדר","אדר ב","ניסן","אייר","סיון","תמוז","אב","אלול"],
				namesAbbr: ["תשרי","חשון","כסלו","טבת","שבט","אדר","אדר ב","ניסן","אייר","סיון","תמוז","אב","אלול"]
			},
			eras: [{"name":"C.E.","start":null,"offset":0}],
			twoDigitYearMax: 5790,
			patterns: {
				d: "dd MMMM yyyy",
				D: "dddd dd MMMM yyyy",
				t: "HH:mm",
				T: "HH:mm:ss",
				f: "dddd dd MMMM yyyy HH:mm",
				F: "dddd dd MMMM yyyy HH:mm:ss",
				M: "dd MMMM",
				Y: "MMMM yyyy"
			},
		    percentsymbol: "%",
            currencysymbol: "$",
            currencysymbolposition: "לפני",
            decimalseparator: '.',
            thousandsseparator: ',',
            pagergotopagestring: "הצג עמוד:",
            pagershowrowsstring: "הצג שורות:",
            pagerrangestring: " מתוך ",
            pagerpreviousbuttonstring: "הקודם",
            pagernextbuttonstring: "הבא",
            pagerfirstbuttonstring: "ראשון",
            pagerlastbuttonstring: "אחרון",
            groupsheaderstring: "Drag a column and drop it here to group by that column",
            sortascendingstring: "מיון בסדר עולה",
            sortdescendingstring: "מיון בסדר יורד",
            sortremovestring: "ביטול מיון",
            groupbystring: "קבץ לפי עמודה",
            groupremovestring: "הסר קיבוץ",
            filterclearstring: "נקה",
            filterstring: "סינון",
            filtershowrowstring: "הצג רשומות היכן ש:",//"Show rows where:",
            filterorconditionstring: "או",
            filterandconditionstring: "וגם",
            filterselectallstring: "(הצג הכל)",
            filterchoosestring: "נא לבחור:",
            //filterstringcomparisonoperators: ['empty', 'not empty', 'enthalten', 'enthalten(match case)',
            //   'does not contain', 'does not contain(match case)', 'starts with', 'starts with(match case)',
            //   'ends with', 'ends with(match case)', 'equal', 'equal(match case)', 'null', 'not null'],
            filterstringcomparisonoperators: ['ריק', 'לא ריק', 'מכיל', 'מכיל(רישיות)',
                    'אינו מכיל', 'אינו מכיל(רישיות)', 'מתחיל ב', 'מתחיל ב(רישיות)',
                    'מסתיים ב', 'מסתיים ב(רישיות)', 'שווה', 'שווה(רישיות)', 'null', 'not null'],
            //filternumericcomparisonoperators: ['equal', 'not equal', 'less than', 'less than or equal', 'greater than', 'greater than or equal', 'null', 'not null'],
            filternumericcomparisonoperators: ['שווה', 'שונה', 'קטן מ', 'קטן או שווה', 'גדול מ', 'גדול או שווה', 'ריק', 'לא ריק'],
            //filterdatecomparisonoperators: ['equal', 'not equal', 'less than', 'less than or equal', 'greater than', 'greater than or equal', 'null', 'not null'],
            filterdatecomparisonoperators: ['שווה', 'שונה', 'קטן מ', 'קטן או שווה', 'גדול מ', 'גדול או שווה', 'ריק', 'לא ריק'],
            //filterbooleancomparisonoperators: ['equal', 'not equal'],
            filterbooleancomparisonoperators: ['שווה', 'שונה'],
            validationstring: "Entered value is not valid",
            validationstring: "הערך שהוקלד אינו תקין",
            //emptydatastring: "No data to display",
            emptydatastring: "לא נמצאו נתונים",
            //filterselectstring: "Select Filter",
            filterselectstring: "בחירת סינון",
            loadtext: "Loading...",
            clearstring: "נקה",
            todaystring: "היום",
            Search: "איתור",
            everpresentrowplaceholder:"הקלד\י-"

		}
	}
});

}( this ));
